services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wagtail_app
    command: >
      sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8000
    expose:
      - "8000"
